version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: portfolio-lucas
    environment:
      POSTGRES_USER: lukedev
      POSTGRES_PASSWORD: lukedev
      POSTGRES_DB: portfolio-lucas
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: