import type { Metadata } from "next"
import { Inter } from "next/font/google"
import SidebarDashboard from "./_components/sidebar-dashboard"
import { EdgeStoreProvider } from "../_lib/edgestore"

export const metadata: Metadata = {
  title: "Portfolio - Lucas",
  description: "Generated by create next app",
}

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ptBr">
      <body className={`${inter.className} antialiased`}>
        <EdgeStoreProvider>
          <div className="flex h-full">
            <SidebarDashboard />
            {children}
          </div>
        </EdgeStoreProvider>
      </body>
    </html>
  )
}
